name: "16 - Working with Matrices"

on:
  workflow_dispatch:

jobs:
  backwards-compatibility:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node_version: [16.x, 18.x, 20.x, 21.x]
        os: [ubuntu-latest, windows-latest]
        tags: [""]
     
    name: "Node ${{ matrix.node_version }} - ${{ matrix.os }} - Tag: ${{ matrix.tags }}"
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Fail if experimental
        if: matrix.tags == 'experimental'
        run: exit 1
      - name: Perform some tests
        run: |
          echo "Running tests on ${{ matrix.os }} and NodeJS ${{ matrix.node_version }}"
          sleep 10
      - name: Upload test results
        run: echo "Uploading test results"