name: "16 - Working with Matrices"

on:
  workflow_dispatch:

jobs:
  backwards-compatibility:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18.x, 20.x, 21.x]
        os: [ubuntu-latest, windows-latest]
    name: "Node ${{ matrix.node_version }} - ${{ matrix.os }}"
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Perform some tests
        run: |
          echo "Running tests on ${{ matrix.os }} and NodeJS ${{ matrix.node_version }}"
          exit 1