name: 01 - Firstworkflow
on: 
    - push
    - workflow_dispatch
jobs:
    echoHello:
        runs-on: ubuntu-latest
        steps:
            - name: Saludar
              run: echo 'Hello world'
    echoBye:
        runs-on: ubuntu-latest
        steps:
            - name: Multi-line bash
              run: |
               echo "I am"
               echo "a multi-line"
               echo "script."
            - name: Decir adios
              run: echo "adios"