name: 01 - First WorkFlow

on:
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Saludar
        run: echo "¡Hola, mundo!"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Paso con éxito
        run: exit 0
      - name: Decir adiós
        run: echo "¡Adiós!"
