name: 14 - Using Cache

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: "Whether to execute cache step"
        type : boolean
        default: true
        required: false
      node-version:
        description: "Node version"
        default: "20.x"
        required: false
        type: choice
        options:
          - "18.x"
          - "20.x"
          - "21.x"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/workflows/my-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ github.event.inputs.node-version }}

      - name: Download cached dependencies
        if: ${{ github.event.inputs.use-cache }}
        id: cache
        uses: actions/cache@v3
        with:
          path: .github/workflows/node_modules
          key: deps-node-modules-${{ hashFiles('.github/workflows/my-app/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Testing
        run: npm run test

      - name: Building
        run: npm run build

      - name: Deploying to nonprod
        if: ${{ github.event.inputs.use-cache }}
        run: echo "Deploying to nonprod"