name: 02 - Eventos

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '* * * * *' # Cada 2 horas
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: ShowTrigger
        run: | 
           echo "El evento que desencadenó este flujo de trabajo fue: ${{ github.event_name }}"