name: 03 - Runners de workflow
on:
  workflow_dispatch

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar SO
        run: |
          echo "Este trabajo se ejecuta en un Runner de Ubuntu"
          echo "El nombre del sistema operativo del Runner es $RUNNER_OS"

  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Mostrar SO
        shell: bash
        run: |
          echo "Este trabajo se ejecuta en un Runner de Windows"
          echo "El nombre del sistema operativo del Runner es $RUNNER_OS"

  mac-echo:
    runs-on: macos-latest
    steps:
      - name: Mostrar SO
        run: |
          echo "Este trabajo se ejecuta en un Runner MacOS"
          echo "El nombre del sistema operativo del Runner es $RUNNER_OS"