name: 12 - Working with Inputs

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Skip deployment and only print build output"
        type: boolean
        default: false
      target:
        description: "Which environment the workflow will target"
        required: true
        type: environment
      tag:
        description: "Release from which to build and deploy"
        default: "v3"
        type: choice
        required: true
        options:
          - v1
          - v2
          - v3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building from tag '${{ github.event.inputs.tag }}'"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success() && !github.event.inputs.dry-run
    environment:
      name: ${{ github.event.inputs.target }}
    steps:
      - name: Deploy
        run: echo "Deploying to '${{ github.event.inputs.target }}'"